site_name: Saiqo
site_url: https://saiqo.fr/
copyright: Copyright &copy; 2024 - 2025 Saiqo

theme:
  name: material
  palette: 
    - scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Rubik
  language: fr

  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path # Only for insiders
    - navigation.top
    
plugins:
  - search:
      lang: fr
  - blog
  - tags

# extra_css:
#   - stylesheets/custom.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/saiqo

nav:
  - Home: index.md
  - Docs: 
    - docs/index.md
    - Proxmox: 
      - Installation: docs/proxmox/index.md
  - Blog: 
    - blog/index.md
  - Tags: tags.md
  - About: about.md  



    

