---
site_name: Saiqo
site_author: Saiqo
site_url: https://saiqo.fr/
copyright: Copyright &copy; 2024 - 2025 Saiqo

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Rubik
  language: fr

  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path # Only for insiders
    - navigation.top
    - content.code.copy


plugins:
  - search:
      lang: fr
  - blog
  - tags

markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# extra_css:
#   - stylesheets/custom.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/saiqo

nav:
  - Home: index.md
  - Docs: 
    - docs/index.md
    - Proxmox: 
      - Installation: docs/proxmox/index.md
  - Blog: 
    - blog/index.md
  - Tags: tags.md
  - About: about.md  



    

